<a href="https://colab.research.google.com/github/chirag300/DataScience/blob/main/Copy_of_Copy_of_numpy_excercise0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Import numpy as np**

In [2]:
import numpy as np

**Create an array of 10 zeros**

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Create an array of 10 ones**

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
a = np.ones(10)

**Create an array of 10 fives**

In [13]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

**Create an array of the integers from 10 to 50**

In [17]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**Create an array of all the even integers from 10 to 50**

In [19]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

**Create a 3x4 matrix with numbers ranging from 0 to 12**

In [20]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

**Create a 3x3 identity matrix**

In [21]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Use Numpy to generate a random number between 0 and 1**

In [26]:
np.random.randn(1)

array([0.81788315])

**Use Numpy to generate an array of 25 random numbers sampled from a standard normal distribution**

In [27]:
np.random.randn(25)

array([-0.02632694, -0.00769814, -0.25372367, -0.26078778, -0.3828829 ,
        0.2543135 , -0.74929129,  0.45533458, -0.65411525, -0.14950386,
        2.0722493 , -0.62617626, -0.27817458, -0.77149376, -0.67195804,
       -1.81288414,  0.1342338 , -0.0416661 , -1.54536464, -2.07578595,
       -0.37393572,  0.00780698, -0.29248323,  0.12337755,  1.14138545])

**Create an (10x10)array having numbers from 0.01 to 1 increasing by 0.01**

In [28]:
np.linspace(0.01,1, 100)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

**Create a (10x10)array of 100 linearly spaces numbers from 0.01 to 1**

In [29]:
np.linspace(0.01,1, 100)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

#Numpy Indexing and Selection

In [75]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [76]:
a[2:: , 2:]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

**extract array**

[
  [12,13,14],

  [17,18,19],

  [22,23,24]
]

array([[0]])

**extract array**

[
  [14, 13, 12],

  [19, 18, 17],

  [24, 23, 22]
]

In [80]:
a[4:1:-1, 4:1:-1]

array([[24, 23, 22],
       [19, 18, 17],
       [14, 13, 12]])

**extract array**

[
  [24, 23, 22],

  [19, 18, 17],

  [14, 13, 12],  
]

#Split Concatinate

In [141]:
ar = np.arange(2,10)
ar

array([2, 3, 4, 5, 6, 7, 8, 9])

**Split array to generate 3 arrays with content**

[2,3,4]

[5, 6]

[]

[7,8,9]

In [143]:
print(np.split(ar, [3, 5]))

[array([2, 3, 4]), array([5, 6]), array([7, 8, 9])]


In [128]:
a = np.array([
              [1,2,3],
              [4,5,6]
])
b = np.array([
              [7,8,9]
])

c= np.concatenate((a,b))
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Concatinate array to create new array with content**

[
  [1,2,3],

  [4,5,6],
  
  [7,8,9]
]

In [129]:
a = np.array([
              [1,2,3],
              [4,5,6]
])
b = np.array([
              [7,8,9, 10],
              [11, 12, 13, 14]
])

c= np.concatenate((a,b), axis = 1)
c 

array([[ 1,  2,  3,  7,  8,  9, 10],
       [ 4,  5,  6, 11, 12, 13, 14]])

**Concatinate array to create new array with content**

[

  [1,2,3, 7,8,9, 10],

  [4,5,6, 11, 12, 13, 14]
  
]

#Broadcasting and Indexing

In [130]:
a = np.array([ 6.,  6.,  5.,  5., 13., 15., 16.,  2.,  3.,  7.,  6., 12., 12.,
       14., 20., 15., 16., 16.,  9., 10., 15.,  1., 10., 18., 12.])

**create new array containing all numbers which are smaller than 10 in ar**

In [131]:
a[a <= 10]

array([ 6.,  6.,  5.,  5.,  2.,  3.,  7.,  6.,  9., 10.,  1., 10.])

**create new array containing all numbers which are in range [3, 11] in ar**

In [132]:
a[(a >= 3) & (a < 11)]

array([ 6.,  6.,  5.,  5.,  3.,  7.,  6.,  9., 10., 10.])

**count how many numbers are minimum in ar**

example for arr = [2, 4, 6, 2, 9, 2]

min is 2

there are 3 occurences of 2

In [133]:
arr = np.array([2, 4, 6, 2, 9, 2])
arr.size
arr[arr==2]

array([2, 2, 2])

**Create an array of length 20 with first 15 numbers equal to 2 and last 5 numbers = -5**

In [134]:
a = np.ones(15)*2
b=  np.ones(5)*-5
c= np.append(a,b)
c

array([ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2., -5., -5., -5., -5., -5.])

In [135]:
mat = np.round(np.random.rand(50)*100).reshape(5,10)
mat

array([[86.,  7., 49., 70., 33., 18., 80., 95., 24., 10.],
       [55.,  9., 14., 56., 64., 84., 79., 88., 85., 27.],
       [32., 26., 28., 48., 26.,  0., 96., 13., 69., 40.],
       [10., 36., 31., 13., 97., 63., 97., 97., 78., 21.],
       [42., 40., 12., 50., 17., 73., 36., 89., 53., 59.]])

**Sum min max of all elements of matrix**

In [136]:
sum = np.min(mat) + np.max(mat)
sum

97.0

**Standard deviation of mat**

In [137]:
np.std(mat)

29.585976407751023

**Sum of all columns of mat**

In [138]:
mat.sum(axis =0)

array([225., 118., 134., 237., 237., 238., 388., 382., 309., 157.])